### ISSUE TITLE
Running React App on local domain

### ISSUE THREAD

**Issue by ozone1864** [lwsjs/local-web-server#113]
I want to run my react app on local domain for example react.app.io
Its not working although I specify the hostname and the folder where I do "npm start"

**Comment by 75lb** [comment]
it's not working how? does it work correctly when you connect via the IP instead of the hostname? What is the error? Does the CLI fail or does it run and you get a 404? a 500? 

Please post enough information (i.e. the full command, the directory structure etc.) to help me reproduce and debug the issue.

**Comment by 75lb** [comment]
waiting for further information.
